import type { Config } from "tailwindcss";
const config: Config = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Core Brand
        "ink-black": "var(--ink-black)",
        onyx: "var(--onyx)",
        graphite: "var(--graphite)",
        "dusty-gray": "var(--dusty-gray)",
        stone: "var(--stone)",
        parchment: "var(--parchment)",
        "vellum-white": "var(--vellum-white)",
        "snow-white": "var(--snow-white)",
        "pale-azure": "var(--pale-azure)",
        "terra-cotta": "var(--terra-cotta)",
        "terra-light": "var(--terra-light)",
        // Surface System
        surface: "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        // Semantic
        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        secondary: "var(--secondary)",
        "secondary-container": "var(--secondary-container)",
        error: "var(--error)",
        "error-container": "var(--error-container)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        // Backward-compatible aliases
        vellum: "var(--vellum-bg)",
        "vellum-surface": "var(--vellum-surface)",
        "vellum-border": "var(--vellum-border)",
        "vellum-border-light": "var(--vellum-border-light)",
        ink: "var(--ink)",
        "ink-secondary": "var(--ink-secondary)",
        "ink-muted": "var(--ink-muted)",
        "ink-faint": "var(--ink-faint)",
        terracotta: "var(--terracotta)",
        danger: "var(--danger)",
        "danger-bg": "var(--danger-bg)",
        "danger-border": "var(--danger-border)",
      },
      fontFamily: {
        "stitch-lora": ["var(--font-stitch-lora)", "Lora", "serif"],
        "stitch-inter": ["var(--font-stitch-inter)", "Inter", "sans-serif"],
        "stitch-mono": ["var(--font-stitch-mono)", "JetBrains Mono", "monospace"],
        // Backward-compatible aliases
        sans: ["var(--font-stitch-inter)", "system-ui", "sans-serif"],
        serif: ["var(--font-stitch-lora)", "Georgia", "serif"],
        mono: ["var(--font-stitch-mono)", "Menlo", "monospace"],
      },
      fontSize: {
        "stitch-display": ["56px", { lineHeight: "1.2", fontWeight: "330" }],
        "stitch-h2": ["30px", { lineHeight: "1.33", fontWeight: "400" }],
        "stitch-h3": ["24px", { lineHeight: "1.33", fontWeight: "400" }],
        "stitch-h4": ["18px", { lineHeight: "1.33", fontWeight: "400" }],
        "stitch-body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "stitch-body-md": ["15px", { lineHeight: "1.4", fontWeight: "400" }],
        "stitch-body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "stitch-caption": ["12px", { lineHeight: "1.33", fontWeight: "400" }],
        "stitch-label-caps": ["11px", { lineHeight: "1.33", fontWeight: "500" }],
      },
      spacing: {
        "stitch-unit": "var(--stitch-unit)",
        "stitch-gap-xs": "var(--stitch-gap-xs)",
        "stitch-gap-md": "var(--stitch-gap-md)",
        "stitch-gap-lg": "var(--stitch-gap-lg)",
        "stitch-section-xl": "var(--stitch-section-xl)",
      },
      maxWidth: {
        "stitch-container-max": "var(--stitch-container-max)",
      },
      borderRadius: {
        "stitch-DEFAULT": "var(--stitch-radius)",
        "stitch-lg": "var(--stitch-radius-lg)",
        "stitch-xl": "var(--stitch-radius-xl)",
        "stitch-full": "var(--stitch-radius-full)",
        "stitch-input": "var(--stitch-radius-input)",
        vellum: "var(--stitch-radius-input)",
      },
    },
  },
  plugins: [],
};
export default config;
