import JSZip from "jszip";
import { DOMAINS } from "@/lib/interview/domains";
import type { DomainId, ProjectContext } from "@/lib/types";

const DOMAIN_DESCRIPTIONS: Record<DomainId, string> = {
  planning:     "project scope and MVP definition",
  architecture: "architecture decisions and patterns",
  database:     "database schema and data model",
  api:          "API contracts and endpoint definitions",
  environment:  "environment strategy and configuration",
  auth:         "authentication and authorization",
  testing:      "testing strategy and coverage targets",
  monitoring:   "monitoring, logging, and alerting",
  frontend:     "frontend architecture and key screens",
  deployment:   "deployment pipeline and infrastructure",
};

function buildReadme(includedFiles: string[]): string {
  const fileList = includedFiles
    .map(f => {
      const domain = DOMAINS.find(d => d.file === f);
      const desc = domain ? DOMAIN_DESCRIPTIONS[domain.id] : "";
      return `- ${f}${desc ? ` — ${desc}` : ""}`;
    })
    .join("\n");

  return `# Project Documentation
Generated by DevDocs AI.

## How to use with AI coding agents
Point your coding agent at this README. It will automatically read the
docs/ folder as context before writing any code.

## Files
${fileList}
`;
}

export async function buildProjectZip(
  _ctx: ProjectContext,
  domainContent: Partial<Record<DomainId, string>>,
): Promise<Blob> {
  const zip = new JSZip();
  const docsFolder = zip.folder("docs")!;
  const includedFiles: string[] = [];

  for (const domain of DOMAINS) {
    const content = domainContent[domain.id];
    if (!content) continue;
    docsFolder.file(domain.file, content);
    includedFiles.push(domain.file);
  }

  docsFolder.file("README.md", buildReadme(includedFiles));

  return zip.generateAsync({ type: "blob" });
}
